### ISSUE TITLE
Not working with react-rails

### ISSUE THREAD

**Issue by mbajur** [apotonick/cells#277]
Hi,
i have encountered an issue when using [react-rails](https://github.com/reactjs/react-rails) with cells. I have no idea if that's a cells or react-rails fault but i have decided to start from here. The thing is, react-rails renders an html tag with attributes containing json content, eg. :

    <%= react_component('HelloMessage', name: 'John') %>
    
    <div data-react-class="HelloMessage" data-react-props="{&quot;name&quot;:&quot;John&quot;}"></div>

And that works well in normal rails views. However, when i'm trying to use `react_component` helper inside cells views, that json part is not getting escaped for some misterious reason. So, for the above example, it gives me:

    <div data-react-class="HelloMessage" data-react-props="{"name":"John"}">

which is obviously wrong and gives me `Uncaught SyntaxError: Unexpected end of input` in chromes dev console (probably because of wrong html syntax produced).

If that's rather react-rails fault, please just let me know and i'm gonna post the same question on their issue tracker. Thanks in advance!

**Comment by apotonick** [comment]
That's a cells "issue". In Cells 4, we do not escape HTML (only defined properties, and I still have to implement this).

Can you link me to the react-rails helper implementation? It sounds as if that helper doesn't call manual escaping properly.

**Comment by mbajur** [comment]
Sure, there you go:
https://github.com/reactjs/react-rails/blob/master/lib/react/rails/view_helper.rb#L9

**Comment by apotonick** [comment]
It looks like `content_tag` does the escaping normally. This is weird?!

**Comment by apotonick** [comment]
This should be fixed in master, you have to make sure you're using cells-erb or whatever format you desire.

**Comment by mbajur** [comment]
Hey, i'm not able to test that because i'm not able to update to 4.x. There are two problems that stops me:

1. When cells-slim is enabled:  
    ```
    /Volumes/HDD/Users/michal/.rvm/gems/ruby-2.1.2/gems/cells-slim-0.0.1/lib/cells/slim.rb:54:in     `<module:Cell>': undefined method `template_engine=' for Cell::ViewModel:Class (NoMethodError)
    ```

2. Devise helper can't be included:
    ```
    class ApplicationCell < Cell::ViewModel
      include FontAwesome::Rails::IconHelper
      include ActionView::Helpers::TranslationHelper
      include Devise::Controllers::Helpers
    end
    ```

    throws 
    `undefined method `helper' for ApplicationCell:Class`

Any idea what can be wrong in here?

**Comment by apotonick** [comment]
Yeah, what about a cells-slim update? :wink: 

We don't support `::helper_method` anymore, as we don't need it: every instance method is a helper in the view.

You can do

```ruby
class ApplicationCell < ..
  def self.helper_method(*)
  end
```

and please open a ticket on Devise and tell them to restructure their helpers, so `::helper_method` doesn't need to be called.

**Comment by mbajur** [comment]
Ok, thanks. I've made it - cells are now at 4.0.0, cells-slim is at 0.0.2 and devise helper works. However - the json is still not escaped properly. And what's more - using `{hash}.to_json` also does not produces escaped json so i'm not even able to use non-helper version of my react components (by non-helper i mean using `div data-react-props={x: 'y'}.to_json` instead of `react_component('HelloMessage', x: 'y')`

**Comment by apotonick** [comment]
Wait a second, `{}.to_json` never produces escaped content - how can that work in the react helper, then?

I guess the problem is in `content_tag` https://github.com/reactjs/react-rails/blob/master/lib/react/rails/view_helper.rb#L25 as I said earlier. If you change that line to the following, it might work:

```ruby
content_tag(html_tag, '', html_options, true, &block)
```

The 4th argument `true` will re-enable escaping. Can you try if that works?

**Comment by mbajur** [comment]
I've tried that but it not change anything. Params are still not escaped. Anyway, the `escape` argument is set to true by default http://apidock.com/rails/ActionView/Helpers/TagHelper/content_tag

I have currently managed to run my code by using `CGI::escapeHTML`:

    div data-react-props=CGI::escapeHTML({x: 'y'}.to_json)

but i still have no idea how to deal with the react helper

**Comment by mbajur** [comment]
Ok, i dealed with it by changing [react view helper props rendering](https://github.com/reactjs/react-rails/blob/master/lib/react/rails/view_helper.rb#L17-L18):

```
html_options[:data].tap do |data|
          props = CGI::escapeHTML(props.is_a?(String) ? props : props.to_json)

          data[:react_class] = name
          data[:react_props] = props
        end
```

I'm gonna open a PR on react_rails page. Thanks for your help!

**Comment by apotonick** [comment]
Can you create a minimal Rails app where I can see this bug in action? I will invest a few minutes and try to find what's the problem, and with an example app this would be a breeze.

Thanks! :beers:

**Comment by mbajur** [comment]
Yes, sure Nick. I'm gonna send you a repo today or tomorrow. Thanks!

**Comment by mbajur** [comment]
Sorry, it took me way more time to prepare that than i expected. Here is the repo: https://github.com/mbajur/cells_with_react

The react-rails gem is included in the repo in untouched form (in `/react-rails` path). You can see that the produced output is not escaped and there is "Uncaught SyntaxError: Unexpected end of input" in Chrome's OI

**Comment by apotonick** [comment]
Man, your repository is excellent, thanks so much, this helped a lot! :heart: 

Here's how to fix it manually:

```ruby
class YourReactCell < Cell::ViewModel
  def tag_options(options, escape = true)
      super(options, true)
    end
end
```

I am thinking about adding this per default to Cells. This will always escape tag options, which should be OK, shouldn't it?

One positive thing I have to say about Rails here is that _AT LEAST_ they introduced this `escape` flag as an argument which makes it quite easy to change behaviour. :grin:

**Comment by apotonick** [comment]
Hmm, I am not sure if we should escape per default, TBH. To me this looks like a very specific thing. I don't have enough experience with all those gems and helpers.

Should we escape tag attributes per default? What do you think, @mbajur ?

**Comment by apotonick** [comment]
I decided to enable it, it makes sense. Thanks for your help! Upgrade to cells-erb 0.0.6 please.

**Comment by mbajur** [comment]
awesome! :)

Should there be an exact same fix for cells-slim ?

**Comment by apotonick** [comment]
Already released! https://github.com/trailblazer/cells-slim/commit/13c8a4c38a32ee60db31d0c4426b93185eb5f57e

**Comment by mbajur** [comment]
awesome!! Now it all works like it should :beers:
